'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option or rebuild the Visual Studio project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "11.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class GlobalText
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Resources.GlobalText", Global.System.Reflection.[Assembly].Load("App_GlobalResources"))
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;!DOCTYPE html PUBLIC &quot;-//W3C//DTD XHTML 1.0 Transitional//EN&quot; &quot;http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd&quot;&gt;
        '''
        '''&lt;html style=&quot;height: 100%&quot; xmlns=&quot;http://www.w3.org/1999/xhtml&quot; &gt;
        '''&lt;head&gt;&lt;title&gt;
        '''	Time &amp; Leave Reporting - Employee Notification
        '''&lt;/title&gt;&lt;/head&gt;
        '''&lt;body style=&quot;margin: auto; text-align: center; height: 100%; &quot;&gt;
        '''
        '''&lt;div id=&quot;container&quot; style=&quot;margin: auto; width: 92%; background-color: white; height: 100%;&quot;&gt;
        '''	&lt;div style=&quot; border-bottom: 0px solid #595959; position: relative; backgroun [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property Email_TimesheetRejected_EmployeeNotification() As String
            Get
                Return ResourceManager.GetString("Email_TimesheetRejected_EmployeeNotification", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;!DOCTYPE html PUBLIC &quot;-//W3C//DTD XHTML 1.0 Transitional//EN&quot; &quot;http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd&quot;&gt;
        '''
        '''&lt;html style=&quot;height: 100%&quot; xmlns=&quot;http://www.w3.org/1999/xhtml&quot; &gt;
        '''&lt;head&gt;&lt;title&gt;
        '''	Time &amp; Leave Reporting - Employee Notification
        '''&lt;/title&gt;&lt;/head&gt;
        '''&lt;body style=&quot;margin: auto; text-align: center; height: 100%; &quot;&gt;
        '''
        '''&lt;div id=&quot;container&quot; style=&quot;margin: auto; width: 92%; background-color: white; height: 100%;&quot;&gt;
        '''	&lt;div style=&quot; border-bottom: 1px solid #595959; position: relative; backgroun [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property Email_TimesheetRejected_SupervisorNotification() As String
            Get
                Return ResourceManager.GetString("Email_TimesheetRejected_SupervisorNotification", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;!DOCTYPE html PUBLIC &quot;-//W3C//DTD XHTML 1.0 Transitional//EN&quot; &quot;http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd&quot;&gt;
        '''
        '''&lt;html style=&quot;height: 100%&quot; xmlns=&quot;http://www.w3.org/1999/xhtml&quot; &gt;
        '''&lt;head&gt;&lt;title&gt;
        '''	Time &amp; Leave Reporting - Employee Notification
        '''&lt;/title&gt;&lt;/head&gt;
        '''&lt;body style=&quot;margin: auto; text-align: center; height: 100%; &quot;&gt;
        '''
        '''&lt;div id=&quot;container&quot; style=&quot;margin: auto; width: 92%; background-color: white; height: 100%;&quot;&gt;
        '''	&lt;div style=&quot; border-bottom: 1px solid #595959; position: relative; backgroun [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property Email_TimesheetSubmitted_SupervisorNotification() As String
            Get
                Return ResourceManager.GetString("Email_TimesheetSubmitted_SupervisorNotification", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;!DOCTYPE html PUBLIC &quot;-//W3C//DTD XHTML 1.0 Transitional//EN&quot; &quot;http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd&quot;&gt;
        '''
        '''&lt;html style=&quot;height: 100%&quot; xmlns=&quot;http://www.w3.org/1999/xhtml&quot; &gt;
        '''&lt;head&gt;&lt;title&gt;
        '''	Time &amp; Leave Reporting - Supervisor Notification
        '''&lt;/title&gt;&lt;/head&gt;
        '''&lt;body style=&quot;margin: auto; text-align: center; height: 100%; &quot;&gt;
        '''
        '''&lt;div id=&quot;container&quot; style=&quot;margin: auto; width: 92%; background-color: white; height: 100%;&quot;&gt;
        '''	&lt;div style=&quot; border-bottom: 1px solid #595959; position: relative; backgro [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property Email_WorkScheduleUpdated_NotifySupervisor() As String
            Get
                Return ResourceManager.GetString("Email_WorkScheduleUpdated_NotifySupervisor", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please enter a valid date..
        '''</summary>
        Friend Shared ReadOnly Property Error_CALENDAR_InvalidDate() As String
            Get
                Return ResourceManager.GetString("Error_CALENDAR_InvalidDate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to An unexpected error has occurred. The appropriate personnel have been notified of this problem and are actively investigating the issue.  Please restart your browser and return to this site to try completing your action again..
        '''</summary>
        Friend Shared ReadOnly Property Error_Error_GenericErrorMessage() As String
            Get
                Return ResourceManager.GetString("Error_Error_GenericErrorMessage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No records were found for the selected pay period.  No file was generated..
        '''</summary>
        Friend Shared ReadOnly Property Error_FileUpload_EmptyUpload() As String
            Get
                Return ResourceManager.GetString("Error_FileUpload_EmptyUpload", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to You need to access this page using the links in this site&apos;s menu..
        '''</summary>
        Friend Shared ReadOnly Property Error_FileUpload_InvalidExportType() As String
            Get
                Return ResourceManager.GetString("Error_FileUpload_InvalidExportType", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to An unknown error has occurred.  The appropriate personnel have been notified with the technical details of this error..
        '''</summary>
        Friend Shared ReadOnly Property Error_FileUpload_UploadError() As String
            Get
                Return ResourceManager.GetString("Error_FileUpload_UploadError", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The specified End Date cannot occur before the specified Start Date.  Please try again..
        '''</summary>
        Friend Shared ReadOnly Property Error_HISTORY_EndDateBeforeStart() As String
            Get
                Return ResourceManager.GetString("Error_HISTORY_EndDateBeforeStart", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please enter a valid End Date..
        '''</summary>
        Friend Shared ReadOnly Property Error_HISTORY_InvalidEndDate() As String
            Get
                Return ResourceManager.GetString("Error_HISTORY_InvalidEndDate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please enter a valid Start Date..
        '''</summary>
        Friend Shared ReadOnly Property Error_HISTORY_InvalidStartDate() As String
            Get
                Return ResourceManager.GetString("Error_HISTORY_InvalidStartDate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please provide a Start and/or End date..
        '''</summary>
        Friend Shared ReadOnly Property Error_HISTORY_NeitherDateProvided() As String
            Get
                Return ResourceManager.GetString("Error_HISTORY_NeitherDateProvided", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please remember to choose which job you want to submit time for before clicking on &apos;Create Timesheet&apos;.
        '''</summary>
        Friend Shared ReadOnly Property Error_HOME_JobNotChosen() As String
            Get
                Return ResourceManager.GetString("Error_HOME_JobNotChosen", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to There are no more pay periods available for this job..
        '''</summary>
        Friend Shared ReadOnly Property Error_HOME_NoMorePayPeriods() As String
            Get
                Return ResourceManager.GetString("Error_HOME_NoMorePayPeriods", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Only active employees are allowed to access this site..
        '''</summary>
        Friend Shared ReadOnly Property Error_LOGIN_InactiveEmployee() As String
            Get
                Return ResourceManager.GetString("Error_LOGIN_InactiveEmployee", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Invalid login credentials. Please try again..
        '''</summary>
        Friend Shared ReadOnly Property Error_LOGIN_InvalidLogin() As String
            Get
                Return ResourceManager.GetString("Error_LOGIN_InvalidLogin", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to PIN can not be blank. Please try again..
        '''</summary>
        Friend Shared ReadOnly Property Error_LOGIN_PINBlank() As String
            Get
                Return ResourceManager.GetString("Error_LOGIN_PINBlank", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to PIN must be numeric. Please try again..
        '''</summary>
        Friend Shared ReadOnly Property Error_LOGIN_PINNotNumeric() As String
            Get
                Return ResourceManager.GetString("Error_LOGIN_PINNotNumeric", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SID can not be blank. Please try again..
        '''</summary>
        Friend Shared ReadOnly Property Error_LOGIN_SIDblank() As String
            Get
                Return ResourceManager.GetString("Error_LOGIN_SIDblank", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SID must be 9 charactes long. Please try again..
        '''</summary>
        Friend Shared ReadOnly Property Error_LOGIN_SIDNot9Char() As String
            Get
                Return ResourceManager.GetString("Error_LOGIN_SIDNot9Char", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to You must select at least one valid (m/d/yyyy) date to search (if no employee is selected)..
        '''</summary>
        Friend Shared ReadOnly Property Error_SEARCHTIMESHEETS_DateNeededToSearch() As String
            Get
                Return ResourceManager.GetString("Error_SEARCHTIMESHEETS_DateNeededToSearch", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The Start Date cannot occur before the End Date..
        '''</summary>
        Friend Shared ReadOnly Property Error_SEARCHTIMESHEETS_EndBeforeStart() As String
            Get
                Return ResourceManager.GetString("Error_SEARCHTIMESHEETS_EndBeforeStart", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to You must select at least one status to search..
        '''</summary>
        Friend Shared ReadOnly Property Error_SEARCHTIMESHEETS_StatusNeeded() As String
            Get
                Return ResourceManager.GetString("Error_SEARCHTIMESHEETS_StatusNeeded", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to You must select at least one type to search..
        '''</summary>
        Friend Shared ReadOnly Property Error_SEARCHTIMESHEETS_TypeNeeded() As String
            Get
                Return ResourceManager.GetString("Error_SEARCHTIMESHEETS_TypeNeeded", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The End Time cannot occur before the Start Time..
        '''</summary>
        Friend Shared ReadOnly Property Error_TimeEntry_EndBeforeStart() As String
            Get
                Return ResourceManager.GetString("Error_TimeEntry_EndBeforeStart", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Your work hours must be greater than the meal time..
        '''</summary>
        Friend Shared ReadOnly Property Error_TimeEntry_MealExceedsShift() As String
            Get
                Return ResourceManager.GetString("Error_TimeEntry_MealExceedsShift", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The times entered overlap with existing entries on this timesheet or another timesheet for the same pay period..
        '''</summary>
        Friend Shared ReadOnly Property Error_TimeEntry_OverlappingEntry() As String
            Get
                Return ResourceManager.GetString("Error_TimeEntry_OverlappingEntry", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The Start and End times cannot be the same..
        '''</summary>
        Friend Shared ReadOnly Property Error_TimeEntry_StartEqualsEnd() As String
            Get
                Return ResourceManager.GetString("Error_TimeEntry_StartEqualsEnd", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The End Date must be a date..
        '''</summary>
        Friend Shared ReadOnly Property Error_TimesheetHistory_InvalidEndDate() As String
            Get
                Return ResourceManager.GetString("Error_TimesheetHistory_InvalidEndDate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The Start Date must be a date..
        '''</summary>
        Friend Shared ReadOnly Property Error_TimesheetHistory_InvalidStartDate() As String
            Get
                Return ResourceManager.GetString("Error_TimesheetHistory_InvalidStartDate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please enter at least one date..
        '''</summary>
        Friend Shared ReadOnly Property Error_TimesheetHistory_StartAndEndDatesEmpty() As String
            Get
                Return ResourceManager.GetString("Error_TimesheetHistory_StartAndEndDatesEmpty", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Timesheets for future pay periods cannot be processed..
        '''</summary>
        Friend Shared ReadOnly Property Error_Timesheet_CannotProcessFuture() As String
            Get
                Return ResourceManager.GetString("Error_Timesheet_CannotProcessFuture", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to You must provide a comment when rejecting a timesheet..
        '''</summary>
        Friend Shared ReadOnly Property Error_TIMESHEET_CommentBlank() As String
            Get
                Return ResourceManager.GetString("Error_TIMESHEET_CommentBlank", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to You cannot submit an empty timesheet..
        '''</summary>
        Friend Shared ReadOnly Property Error_TIMESHEET_EmptyTimesheet() As String
            Get
                Return ResourceManager.GetString("Error_TIMESHEET_EmptyTimesheet", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The timesheet ID is invalid..
        '''</summary>
        Friend Shared ReadOnly Property Error_TIMESHEET_InvalidTSID() As String
            Get
                Return ResourceManager.GetString("Error_TIMESHEET_InvalidTSID", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please enter a remark if you have misc. time in your timesheet..
        '''</summary>
        Friend Shared ReadOnly Property Error_TIMESHEET_NeedRemark() As String
            Get
                Return ResourceManager.GetString("Error_TIMESHEET_NeedRemark", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to You do not have permission to view this timesheet..
        '''</summary>
        Friend Shared ReadOnly Property Error_TIMESHEET_NoPermission() As String
            Get
                Return ResourceManager.GetString("Error_TIMESHEET_NoPermission", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to You don&apos;t have permission to edit this timesheet..
        '''</summary>
        Friend Shared ReadOnly Property Error_TIMESHEET_NotEditable() As String
            Get
                Return ResourceManager.GetString("Error_TIMESHEET_NotEditable", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to You can only edit your own timesheets..
        '''</summary>
        Friend Shared ReadOnly Property Error_TIMESHEET_NotOwner() As String
            Get
                Return ResourceManager.GetString("Error_TIMESHEET_NotOwner", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The Timesheet ID requested was not found..
        '''</summary>
        Friend Shared ReadOnly Property Error_TIMESHEET_TSIDNotFound() As String
            Get
                Return ResourceManager.GetString("Error_TIMESHEET_TSIDNotFound", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to You cannot have more than 24 hours of leave for a single day..
        '''</summary>
        Friend Shared ReadOnly Property Error_TSFullTime_24HoursExceeded() As String
            Get
                Return ResourceManager.GetString("Error_TSFullTime_24HoursExceeded", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to This selection exceeds your available balance (including timesheets not yet processed by payroll)..
        '''</summary>
        Friend Shared ReadOnly Property Error_TSFullTime_BalanceExceeded() As String
            Get
                Return ResourceManager.GetString("Error_TSFullTime_BalanceExceeded", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Compensatory (comp.) time entries may not be deleted or reduced while unprocessed vacation entries exist..
        '''</summary>
        Friend Shared ReadOnly Property Error_TSFullTime_InvalidCompTimeUpdate() As String
            Get
                Return ResourceManager.GetString("Error_TSFullTime_InvalidCompTimeUpdate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to You must enter a valid value for &apos;Hours&apos;..
        '''</summary>
        Friend Shared ReadOnly Property Error_TSFullTime_InvalidHours() As String
            Get
                Return ResourceManager.GetString("Error_TSFullTime_InvalidHours", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to You can&apos;t have more than two numbers after the decimal point. .
        '''</summary>
        Friend Shared ReadOnly Property Error_TSFullTime_InvalidHours_Decimal() As String
            Get
                Return ResourceManager.GetString("Error_TSFullTime_InvalidHours_Decimal", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please enter hours that are greater than 0 and less than or equal to 24. .
        '''</summary>
        Friend Shared ReadOnly Property Error_TSFullTime_InvalidHours_Greater24Less0() As String
            Get
                Return ResourceManager.GetString("Error_TSFullTime_InvalidHours_Greater24Less0", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please enter a number..
        '''</summary>
        Friend Shared ReadOnly Property Error_TSFullTime_InvalidHours_NonNumeric() As String
            Get
                Return ResourceManager.GetString("Error_TSFullTime_InvalidHours_NonNumeric", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Overtime values are limited to two decimal places..
        '''</summary>
        Friend Shared ReadOnly Property Error_TSFullTime_InvalidOTPrecision() As String
            Get
                Return ResourceManager.GetString("Error_TSFullTime_InvalidOTPrecision", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The split of overtime does not add up to the total acrued overtime..
        '''</summary>
        Friend Shared ReadOnly Property Error_TSFulltime_InvalidOTSplit() As String
            Get
                Return ResourceManager.GetString("Error_TSFulltime_InvalidOTSplit", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Overtime values must be numeric..
        '''</summary>
        Friend Shared ReadOnly Property Error_TSFullTime_InvalidOTValue() As String
            Get
                Return ResourceManager.GetString("Error_TSFullTime_InvalidOTValue", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Remarks cannot be blank..
        '''</summary>
        Friend Shared ReadOnly Property Error_TSFullTime_InvalidRemarkLength() As String
            Get
                Return ResourceManager.GetString("Error_TSFullTime_InvalidRemarkLength", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Positive time (&apos;W&apos;) reporting is limited to 40 hours per week..
        '''</summary>
        Friend Shared ReadOnly Property Error_TSFulltime_PositiveTimeWeekLimitExceeded() As String
            Get
                Return ResourceManager.GetString("Error_TSFulltime_PositiveTimeWeekLimitExceeded", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to You have entered a leave type which requires a remark before submitting your timesheet..
        '''</summary>
        Friend Shared ReadOnly Property Error_TSFullTime_RemarkRequired() As String
            Get
                Return ResourceManager.GetString("Error_TSFullTime_RemarkRequired", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to You must use your compensatory (comp.) time before using your vacation. .
        '''</summary>
        Friend Shared ReadOnly Property Error_TSFullTime_VacationBeforeComp() As String
            Get
                Return ResourceManager.GetString("Error_TSFullTime_VacationBeforeComp", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to This selection exceeds your available balance, including timesheets not yet processed by Payroll..
        '''</summary>
        Friend Shared ReadOnly Property Error_TSPartTime_BalanceExceeded() As String
            Get
                Return ResourceManager.GetString("Error_TSPartTime_BalanceExceeded", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &apos; is not a valid budget allocation amount..
        '''</summary>
        Friend Shared ReadOnly Property Error_TSParttime_InvalidAllocationText() As String
            Get
                Return ResourceManager.GetString("Error_TSParttime_InvalidAllocationText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to budget allocation amounts do not equal the total hours earned for the entry. .
        '''</summary>
        Friend Shared ReadOnly Property Error_TSParttime_InvalidEntryAllocation() As String
            Get
                Return ResourceManager.GetString("Error_TSParttime_InvalidEntryAllocation", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Budget allocation amounts do not equal the total hours earned for this timesheet..
        '''</summary>
        Friend Shared ReadOnly Property Error_TSParttime_InvalidTimesheetAllocation() As String
            Get
                Return ResourceManager.GetString("Error_TSParttime_InvalidTimesheetAllocation", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to A meal break cannot be claimed on shifts less than 5 hours..
        '''</summary>
        Friend Shared ReadOnly Property Error_TSParttime_MealBreakNotAllowed() As String
            Get
                Return ResourceManager.GetString("Error_TSParttime_MealBreakNotAllowed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to This timesheet does not have any budgets associated with it.  Please contact Payroll for assistance..
        '''</summary>
        Friend Shared ReadOnly Property Error_TSParttime_NoBudget() As String
            Get
                Return ResourceManager.GetString("Error_TSParttime_NoBudget", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Budget allocation amounts specified using percents must be in whole numbers..
        '''</summary>
        Friend Shared ReadOnly Property Error_TSParttime_PercentAllocationMustBeWholeNumber() As String
            Get
                Return ResourceManager.GetString("Error_TSParttime_PercentAllocationMustBeWholeNumber", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to This timesheet  must first be rejected in order to update the budget information..
        '''</summary>
        Friend Shared ReadOnly Property Error_UpdateTimesheet_BudgetNotEditable() As String
            Get
                Return ResourceManager.GetString("Error_UpdateTimesheet_BudgetNotEditable", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Budget numbers must be 14 characters in length and only contain numbers and letters..
        '''</summary>
        Friend Shared ReadOnly Property Error_UpdateTimesheet_InvalidBudgetNumber() As String
            Get
                Return ResourceManager.GetString("Error_UpdateTimesheet_InvalidBudgetNumber", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Pay Rate must be specified as a number with no more than two decimal places..
        '''</summary>
        Friend Shared ReadOnly Property Error_UpdateTimesheet_InvalidPayRate() As String
            Get
                Return ResourceManager.GetString("Error_UpdateTimesheet_InvalidPayRate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Invalid Timesheet ID..
        '''</summary>
        Friend Shared ReadOnly Property Error_UpdateTimesheet_InvalidTimesheetID() As String
            Get
                Return ResourceManager.GetString("Error_UpdateTimesheet_InvalidTimesheetID", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Every timesheet must have at least one budget..
        '''</summary>
        Friend Shared ReadOnly Property Error_UpdateTimesheet_OneBudgetNecessary() As String
            Get
                Return ResourceManager.GetString("Error_UpdateTimesheet_OneBudgetNecessary", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Timesheet ID was not found..
        '''</summary>
        Friend Shared ReadOnly Property Error_UpdateTimesheet_TimesheetIDNotFound() As String
            Get
                Return ResourceManager.GetString("Error_UpdateTimesheet_TimesheetIDNotFound", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Work schedules are limited to 40 hours per week..
        '''</summary>
        Friend Shared ReadOnly Property Error_WorkSchedule_40WHoursExceeded() As String
            Get
                Return ResourceManager.GetString("Error_WorkSchedule_40WHoursExceeded", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The times entered overlap with existing entries on your work schedule..
        '''</summary>
        Friend Shared ReadOnly Property Error_WorkSchedule_OverlappingEntry() As String
            Get
                Return ResourceManager.GetString("Error_WorkSchedule_OverlappingEntry", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to There are no timesheets that can be exported into a file at this time..
        '''</summary>
        Friend Shared ReadOnly Property Note_FileUpload_NoTimesheets() As String
            Get
                Return ResourceManager.GetString("Note_FileUpload_NoTimesheets", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to A note to JAWS Users:  To make this page easier to read and understand using the JAWS software, please go to JAWS settings and turn on what&apos;s called the“Abbreviation Expand” setting.  Here is how:
        '''1. Go to the JAWS Verbosity dialog by pressing Insert and the letter V.
        '''2. Expand the &quot;Text Options&quot;
        '''3. Select &quot;Abbreviations Expand&quot;
        '''4. Press spacebar to toggle it on if it isn&apos;t already..
        '''</summary>
        Friend Shared ReadOnly Property Note_TSFullTime_JawsUsers() As String
            Get
                Return ResourceManager.GetString("Note_TSFullTime_JawsUsers", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Approve Timesheets, Time and Leave Reporting.
        '''</summary>
        Friend Shared ReadOnly Property PageTitle_APPROVETIMESHEETS() As String
            Get
                Return ResourceManager.GetString("PageTitle_APPROVETIMESHEETS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Calendar, Time and Leave Reporting.
        '''</summary>
        Friend Shared ReadOnly Property PageTitle_CALENDAR() As String
            Get
                Return ResourceManager.GetString("PageTitle_CALENDAR", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Delegated Timesheets, Time and Leave Reporting.
        '''</summary>
        Friend Shared ReadOnly Property PageTitle_DELEGATEDTIMESHEETS() As String
            Get
                Return ResourceManager.GetString("PageTitle_DELEGATEDTIMESHEETS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Delegation, Time and Leave Reporting.
        '''</summary>
        Friend Shared ReadOnly Property PageTitle_DELEGATION() As String
            Get
                Return ResourceManager.GetString("PageTitle_DELEGATION", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Edit Timesheet, Time and Leave Reporting.
        '''</summary>
        Friend Shared ReadOnly Property PageTitle_EDITTIMESHEET() As String
            Get
                Return ResourceManager.GetString("PageTitle_EDITTIMESHEET", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Employees&apos; Balance, Time and Leave Reporting.
        '''</summary>
        Friend Shared ReadOnly Property PageTitle_EMPLOYEESBALANCE() As String
            Get
                Return ResourceManager.GetString("PageTitle_EMPLOYEESBALANCE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Error, Time and Leave Reporting.
        '''</summary>
        Friend Shared ReadOnly Property PageTitle_ERROR() As String
            Get
                Return ResourceManager.GetString("PageTitle_ERROR", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to File Export, Time and Leave Reporting.
        '''</summary>
        Friend Shared ReadOnly Property PageTitle_FileExport() As String
            Get
                Return ResourceManager.GetString("PageTitle_FileExport", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Home, Time and Leave Reporting.
        '''</summary>
        Friend Shared ReadOnly Property PageTitle_HOME() As String
            Get
                Return ResourceManager.GetString("PageTitle_HOME", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Leave Balance, Time and Leave Reporting.
        '''</summary>
        Friend Shared ReadOnly Property PageTitle_LEAVEBALANCE() As String
            Get
                Return ResourceManager.GetString("PageTitle_LEAVEBALANCE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Log In, Time and Leave Reporting.
        '''</summary>
        Friend Shared ReadOnly Property PageTitle_LOGIN() As String
            Get
                Return ResourceManager.GetString("PageTitle_LOGIN", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Search Employees, Time and Leave Reporting.
        '''</summary>
        Friend Shared ReadOnly Property PageTitle_SEARCHEMPLOYEES() As String
            Get
                Return ResourceManager.GetString("PageTitle_SEARCHEMPLOYEES", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Search Timesheets, Time and Leave Reporting.
        '''</summary>
        Friend Shared ReadOnly Property PageTitle_SEARCHTIMESHEETS() As String
            Get
                Return ResourceManager.GetString("PageTitle_SEARCHTIMESHEETS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Timesheet, Time and Leave Reporting.
        '''</summary>
        Friend Shared ReadOnly Property PageTitle_TIMESHEET() As String
            Get
                Return ResourceManager.GetString("PageTitle_TIMESHEET", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Timesheet History, Time and Leave Reporting.
        '''</summary>
        Friend Shared ReadOnly Property PageTitle_TIMESHEETHISTORY() As String
            Get
                Return ResourceManager.GetString("PageTitle_TIMESHEETHISTORY", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Unprocessed Timesheets, Time and Leave Reporting.
        '''</summary>
        Friend Shared ReadOnly Property PageTitle_UNPROCESSEDTIMESHEETS() As String
            Get
                Return ResourceManager.GetString("PageTitle_UNPROCESSEDTIMESHEETS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Update Timesheet, Time and Leave Reporting.
        '''</summary>
        Friend Shared ReadOnly Property PageTitle_UpdateTimesheet() As String
            Get
                Return ResourceManager.GetString("PageTitle_UpdateTimesheet", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to View Timesheet, Time and Leave Reporting.
        '''</summary>
        Friend Shared ReadOnly Property PageTitle_VIEWTIMESHEET() As String
            Get
                Return ResourceManager.GetString("PageTitle_VIEWTIMESHEET", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Work Hours, Time and Leave Reporting.
        '''</summary>
        Friend Shared ReadOnly Property PageTitle_WORKHOURS() As String
            Get
                Return ResourceManager.GetString("PageTitle_WORKHOURS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to File generation successful.  File name:.
        '''</summary>
        Friend Shared ReadOnly Property Success_FileUpload_UploadComplete() As String
            Get
                Return ResourceManager.GetString("Success_FileUpload_UploadComplete", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Budget number successfully added to this timesheet..
        '''</summary>
        Friend Shared ReadOnly Property Success_UpdateTimesheet_BudgetNumberAdded() As String
            Get
                Return ResourceManager.GetString("Success_UpdateTimesheet_BudgetNumberAdded", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The supervisor for this timesheet has been successfully updated..
        '''</summary>
        Friend Shared ReadOnly Property Success_UpdateTimesheet_SupervisorUpdated() As String
            Get
                Return ResourceManager.GetString("Success_UpdateTimesheet_SupervisorUpdated", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Your work hours have been successfully submited and will be available for import when working with your timesheets..
        '''</summary>
        Friend Shared ReadOnly Property Success_WORKHOURS_Approved() As String
            Get
                Return ResourceManager.GetString("Success_WORKHOURS_Approved", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to This timesheet has {0} hour(s) of leave. As a reminder, leave hours cannot be allocated to budgets of type {1}..
        '''</summary>
        Friend Shared ReadOnly Property Warning_LeaveTotalWithInvalidBudgetEarningType() As String
            Get
                Return ResourceManager.GetString("Warning_LeaveTotalWithInvalidBudgetEarningType", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
