'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.3082
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On



Partial Public Class TS_FullTime

    Protected WithEvents uclFeedback As Global.TLR.Feedback
    Protected WithEvents uclTSActionLog As Global.TLR.TSActionLog

    Protected WithEvents litEntryHeader As Global.System.Web.UI.WebControls.Literal
    Protected WithEvents lblTSPeriod As Global.System.Web.UI.WebControls.Label
    Protected WithEvents lblStatus As Global.System.Web.UI.WebControls.Label
    Protected WithEvents lblName As Global.System.Web.UI.WebControls.Label
    Protected WithEvents lblSupervisor As Global.System.Web.UI.WebControls.Label
    Protected WithEvents lblJobTitle As Global.System.Web.UI.WebControls.Label
    Protected WithEvents lblOTHours As Global.System.Web.UI.WebControls.Label
  Protected WithEvents lblDueDate As Global.System.Web.UI.WebControls.Label
  Protected WithEvents lblCompTimeMsg As Global.System.Web.UI.WebControls.Label
    Protected WithEvents lblDelegationInfo As Label

    Protected WithEvents ddlDate As Global.System.Web.UI.WebControls.DropDownList
    Protected WithEvents ddlEntryType As Global.System.Web.UI.WebControls.DropDownList

    Protected WithEvents txtHours As Global.System.Web.UI.WebControls.TextBox
    Protected WithEvents txtRemark As Global.System.Web.UI.WebControls.TextBox
    Protected WithEvents txtComment As Global.System.Web.UI.WebControls.TextBox
    Protected WithEvents txtOT_Pay As Global.System.Web.UI.WebControls.TextBox
    Protected WithEvents txtOT_Convert As Global.System.Web.UI.WebControls.TextBox

  Protected WithEvents rptHolidays As Global.System.Web.UI.WebControls.Repeater
  Protected WithEvents rptRemarks As Global.System.Web.UI.WebControls.Repeater
    Protected WithEvents rptWeeks As Global.System.Web.UI.WebControls.Repeater
    Protected WithEvents rptTimesheetTotals As Global.System.Web.UI.WebControls.Repeater

    Protected WithEvents pnlEditRemark As Global.System.Web.UI.WebControls.Panel
    Protected WithEvents pnlNoWorkSchedule As Global.System.Web.UI.WebControls.Panel
    Protected WithEvents pnlImportHours As Global.System.Web.UI.WebControls.Panel
    Protected WithEvents pnlTimesheetTotals As Global.System.Web.UI.WebControls.Panel
    Protected WithEvents pnlWorkScheduleNotApproved As Global.System.Web.UI.WebControls.Panel
    Protected WithEvents pnlEntryDetails As Global.System.Web.UI.WebControls.Panel
    Protected WithEvents pnlApprovalInterface As Global.System.Web.UI.WebControls.Panel
    Protected WithEvents pnlSubmissionInterface As Global.System.Web.UI.WebControls.Panel
    Protected WithEvents pnlTSDetails As Global.System.Web.UI.WebControls.Panel
    Protected WithEvents pnlOvertime As Global.System.Web.UI.WebControls.Panel

    Protected WithEvents btnSaveRemark As Global.System.Web.UI.WebControls.Button
  Protected WithEvents btnSubmitTimesheet As Global.System.Web.UI.WebControls.Button
  Protected WithEvents btnSubmitTimesheetDisabled As Global.System.Web.UI.WebControls.Button
    Protected WithEvents btnDeleteTimesheet As Global.System.Web.UI.WebControls.Button
    Protected WithEvents btnEnterWorkHours As Global.System.Web.UI.WebControls.Button
    Protected WithEvents btnAskMeLater As Global.System.Web.UI.WebControls.Button
    Protected WithEvents btnImportWorkHours As Global.System.Web.UI.WebControls.Button
    Protected WithEvents btnDoNotImportWorkHours As Global.System.Web.UI.WebControls.Button
    Protected WithEvents btnWorkScheduleContinueEdit As Global.System.Web.UI.WebControls.Button
    Protected WithEvents btnAddEntry As Global.System.Web.UI.WebControls.Button
    Protected WithEvents btnUpdateEntry As Global.System.Web.UI.WebControls.Button
    Protected WithEvents btnDeleteEntry As Global.System.Web.UI.WebControls.Button
    Protected WithEvents btnCancelUpdate As Global.System.Web.UI.WebControls.Button
    Protected WithEvents btnAddRemark As Global.System.Web.UI.WebControls.Button
    Protected WithEvents btnCancelRemarkUpdate As Global.System.Web.UI.WebControls.Button
    Protected WithEvents btnApproveTimesheet As Global.System.Web.UI.WebControls.Button
    Protected WithEvents btnRejectTimesheet As Global.System.Web.UI.WebControls.Button

    Protected WithEvents spanApprove As HtmlGenericControl
    Protected WithEvents h2Remarks As HtmlGenericControl
    Protected WithEvents h2Overtime As HtmlGenericControl
    Protected WithEvents pOT As HtmlGenericControl
    Protected WithEvents pVacationApproval As HtmlGenericControl
  Protected WithEvents liUpdateTimesheet As HtmlGenericControl
  Protected WithEvents liGenericHoliday As HtmlGenericControl
End Class
