'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class TS_PartTime
    
    '''<summary>
    '''uclFeedback control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents uclFeedback As Global.TLR.Feedback
    
    '''<summary>
    '''lblTSPeriod control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTSPeriod As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblDelegationInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDelegationInfo As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''pnlTSDetails control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlTSDetails As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''litTSDetails control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litTSDetails As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''lblStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblStatus As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblName As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblSupervisor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSupervisor As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblJobTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblJobTitle As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblPayRate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPayRate As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblBudget control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblBudget As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblDueDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDueDate As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''liUpdateTimesheet control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents liUpdateTimesheet As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''pnlEntryDetails control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlEntryDetails As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''litHeader control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litHeader As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''ddlDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlDate As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''ddlStartHour control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlStartHour As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''ddlStartMinute control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlStartMinute As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''ddlStartAMPM control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlStartAMPM As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''ddlEndHour control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlEndHour As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''ddlEndMinute control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlEndMinute As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''ddlEndAMPM control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlEndAMPM As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''ddlMealTime control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlMealTime As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''liEntryType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents liEntryType As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''chkbxEnterType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkbxEnterType As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''ddlEntryType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlEntryType As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''btnAddEntry control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAddEntry As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnUpdateEntry control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnUpdateEntry As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnDeleteEntry control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnDeleteEntry As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnCancelUpdate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCancelUpdate As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''pnlTimesheetTotals control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlTimesheetTotals As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''rptTimesheetTotals control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rptTimesheetTotals As Global.System.Web.UI.WebControls.Repeater
    
    '''<summary>
    '''ddlBudgetAllocationSplitTypePerEntry control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlBudgetAllocationSplitTypePerEntry As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''rptWeeks control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rptWeeks As Global.System.Web.UI.WebControls.Repeater
    
    '''<summary>
    '''lblGrandTotalHours control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblGrandTotalHours As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblLeaveTotalHours control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLeaveTotalHours As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''h2Remarks control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents h2Remarks As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''rptRemarks control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rptRemarks As Global.System.Web.UI.WebControls.Repeater
    
    '''<summary>
    '''btnAddRemark control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAddRemark As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''pnlEditRemark control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlEditRemark As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''txtRemark control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRemark As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''btnSaveRemark control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSaveRemark As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnCancelRemarkUpdate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCancelRemarkUpdate As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''pnlBudgetAllocation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlBudgetAllocation As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''lblBudgetAllocationTotalHours control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblBudgetAllocationTotalHours As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblLeaveWarning control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLeaveWarning As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''fsSplitBudgets control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fsSplitBudgets As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''ddlBudgetAllocationSplitType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlBudgetAllocationSplitType As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''lblBudgetSplit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblBudgetSplit As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''rptBudgetAllocationSelection control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rptBudgetAllocationSelection As Global.System.Web.UI.WebControls.Repeater
    
    '''<summary>
    '''pnlSubmissionInterface control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlSubmissionInterface As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''btnSubmitTimesheet control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSubmitTimesheet As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnDeleteTimesheet control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnDeleteTimesheet As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''pnlApprovalInterface control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlApprovalInterface As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''btnApproveTimesheet control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnApproveTimesheet As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnRejectTimesheet control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnRejectTimesheet As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''txtComment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtComment As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''uclTSActionLog control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents uclTSActionLog As Global.TLR.TSActionLog
End Class
