'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.3074
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On



Partial Public Class ApproveTimesheets

    '''<summary>
    '''pnlPrimaryApproval control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlPrimaryApproval As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''pNoTimesheets_Primary control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pNoTimesheets_Primary As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''rptPrimaryApproval control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rptPrimaryApproval As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''pnlAlternateApproval control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlAlternateApproval As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''pNoTimesheets_Alternate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pNoTimesheets_Alternate As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''rptAlternateApproval control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rptAlternateApproval As Global.System.Web.UI.WebControls.Repeater
End Class
