'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class DelegatedTimesheets
    
    '''<summary>
    '''uclFeedback control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents uclFeedback As Global.TLR.Feedback
    
    '''<summary>
    '''pnlActiveTimesheets control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlActiveTimesheets As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''lblNoActiveTimesheets control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNoActiveTimesheets As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''rptActiveTimesheets control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rptActiveTimesheets As Global.System.Web.UI.WebControls.Repeater
    
    '''<summary>
    '''pnlCreateTimesheet control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlCreateTimesheet As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''rptJobList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rptJobList As Global.System.Web.UI.WebControls.Repeater
    
    '''<summary>
    '''btnCreateTimeSheet control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCreateTimeSheet As Global.System.Web.UI.WebControls.Button
End Class
