'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class _Default
    
    '''<summary>
    '''uclFeedback control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents uclFeedback As Global.TLR.Feedback
    
    '''<summary>
    '''pnlLeave control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlLeave As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''pnlActiveTimesheets control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlActiveTimesheets As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''lblNoActiveTimesheets control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNoActiveTimesheets As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''rptActiveTimesheets control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rptActiveTimesheets As Global.System.Web.UI.WebControls.Repeater
    
    '''<summary>
    '''pnlCreateTimesheet control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlCreateTimesheet As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''lblNoActiveJobs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNoActiveJobs As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''rptJobList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rptJobList As Global.System.Web.UI.WebControls.Repeater
    
    '''<summary>
    '''btnCreateTimeSheet control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCreateTimeSheet As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''pnlWorkSchedule control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlWorkSchedule As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''pnlWorkScheduleOffer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlWorkScheduleOffer As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''btnEnterWorkSchedule control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnEnterWorkSchedule As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''pnlWorkScheduleCurrent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlWorkScheduleCurrent As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''rptWorkSchedule control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rptWorkSchedule As Global.System.Web.UI.WebControls.Repeater
    
    '''<summary>
    '''btnEditWorkSchedule control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnEditWorkSchedule As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''pnlWorkScheduleNotApproved control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlWorkScheduleNotApproved As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''btnWorkScheduleContinueEdit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnWorkScheduleContinueEdit As Global.System.Web.UI.WebControls.Button
End Class
