'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class mpDefault
    
    '''<summary>
    '''Head1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Head1 As Global.System.Web.UI.HtmlControls.HtmlHead
    
    '''<summary>
    '''litAppVersion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litAppVersion As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''lblUserFullName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblUserFullName As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''btnLogOut control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnLogOut As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''liLeaveBalance control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents liLeaveBalance As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''liWorkHours control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents liWorkHours As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''liSupervisor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents liSupervisor As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''liManageTimesheets control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents liManageTimesheets As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''litSupervisorReportLink control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litSupervisorReportLink As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''liPayroll control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents liPayroll As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''litPayrollReportLink control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litPayrollReportLink As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''litSupervisorReportLinkPayroll control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litSupervisorReportLinkPayroll As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''liFinancialAid control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents liFinancialAid As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''liFinance control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents liFinance As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''liHR control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents liHR As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''cphBody control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cphBody As Global.System.Web.UI.WebControls.ContentPlaceHolder
End Class
