'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.4927
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On



Partial Public Class SearchEmployees

  '''<summary>
  '''ToolkitScriptManager control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents ToolkitScriptManager As Global.AjaxControlToolkit.ToolkitScriptManager

  '''<summary>
  '''uclFeedback control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents uclFeedback As Global.TLR.Feedback

  '''<summary>
  '''hPageHeader control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents hPageHeader As Global.System.Web.UI.HtmlControls.HtmlGenericControl

  '''<summary>
  '''pnlEmployeeLookup control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents pnlEmployeeLookup As Global.System.Web.UI.WebControls.Panel

  '''<summary>
  '''txtUserSearch control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents txtUserSearch As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''aceNameOrSID control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents aceNameOrSID As Global.AjaxControlToolkit.AutoCompleteExtender

  '''<summary>
  '''btnSearchUsers control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents btnSearchUsers As Global.System.Web.UI.WebControls.Button

  '''<summary>
  '''pNoSearchResults control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents pNoSearchResults As Global.System.Web.UI.HtmlControls.HtmlGenericControl

  '''<summary>
  '''pNoFulltimeEmployees control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents pNoFulltimeEmployees As Global.System.Web.UI.HtmlControls.HtmlGenericControl

  '''<summary>
  '''pnlUserList control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents pnlUserList As Global.System.Web.UI.WebControls.Panel

  '''<summary>
  '''rptUserSearchResults control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents rptUserSearchResults As Global.System.Web.UI.WebControls.Repeater

  '''<summary>
  '''pnlEmployeeDetails control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents pnlEmployeeDetails As Global.System.Web.UI.WebControls.Panel

  '''<summary>
  '''lblEmployeeName control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents lblEmployeeName As Global.System.Web.UI.WebControls.Label

  '''<summary>
  '''btnSelectNewEmployee control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents btnSelectNewEmployee As Global.System.Web.UI.WebControls.Button

  '''<summary>
  '''pnlWorkSchedule control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents pnlWorkSchedule As Global.System.Web.UI.WebControls.Panel

  '''<summary>
  '''lblWorkScheduleStatus control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents lblWorkScheduleStatus As Global.System.Web.UI.WebControls.Label

  '''<summary>
  '''rptWorkSchedule control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents rptWorkSchedule As Global.System.Web.UI.WebControls.Repeater

  '''<summary>
  '''pnlLeaveBalances control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents pnlLeaveBalances As Global.System.Web.UI.WebControls.Panel

  '''<summary>
  '''rptLeaveBalance control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents rptLeaveBalance As Global.System.Web.UI.WebControls.Repeater

  '''<summary>
  '''ddlViewPeriod control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents ddlViewPeriod As Global.System.Web.UI.WebControls.DropDownList

  '''<summary>
  '''btnViewPeriod control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents btnViewPeriod As Global.System.Web.UI.WebControls.Button

  '''<summary>
  '''rptTimesheets control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents rptTimesheets As Global.System.Web.UI.WebControls.Repeater
End Class
