'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.4927
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On



Partial Public Class UnprocessedTimesheets

  '''<summary>
  '''uclFeedback control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents uclFeedback As Global.TLR.Feedback

  '''<summary>
  '''lblPageHeader control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents lblPageHeader As Global.System.Web.UI.WebControls.Label

  '''<summary>
  '''pNoUnprocessedTimesheets control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents pNoUnprocessedTimesheets As Global.System.Web.UI.HtmlControls.HtmlGenericControl

  '''<summary>
  '''rptTimesheets control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents rptTimesheets As Global.System.Web.UI.WebControls.Repeater
End Class
